=== Randy-Bruce/XML/JeuxOlympique/public_html/jeuxOlympique.dtd
<!ELEMENT oui (tableau)>
<!ELEMENT tableau (ligne*)>
<!ELEMENT ligne (pays,medaille,medaille,medaille,totalMedaille?)>
<!ELEMENT pays EMPTY>
<!ELEMENT medaille (#PCDATA)>
<!ELEMENT totalMedaille (#PCDATA)>


<!ATTLIST pays nomDePays ( USA | GrandeBretagne | Chine | Russie | Allemagne | Japon | France | CoreeDuSud | Italie | Australie ) #REQUIRED >
<!ATTLIST medaille typeDeMedaille (Or | Argent | Bronze) #REQUIRED >

=== Randy-Bruce/XML/JeuxOlympique/public_html/jeuxOlympique.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE oui SYSTEM "jeuxOlympique.dtd">
<?xml-stylesheet href="jeuxOlympique.xsl" type="text/xsl" ?>
<oui>
    <tableau>
        <ligne>
            <pays nomDePays="USA"></pays>
            <medaille typeDeMedaille="Or">46</medaille>
            <medaille typeDeMedaille="Argent">37</medaille>
            <medaille typeDeMedaille="Bronze">38</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="GrandeBretagne"></pays>
            <medaille typeDeMedaille="Or">27</medaille>
            <medaille typeDeMedaille="Argent">23</medaille>
            <medaille typeDeMedaille="Bronze">17</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="Chine"></pays>
            <medaille typeDeMedaille="Or">26</medaille>
            <medaille typeDeMedaille="Argent">18</medaille>
            <medaille typeDeMedaille="Bronze">26            
            </medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="Russie"></pays>
            <medaille typeDeMedaille="Or">19</medaille>
            <medaille typeDeMedaille="Argent">18</medaille>
            <medaille typeDeMedaille="Bronze">19</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="Allemagne"></pays>
            <medaille typeDeMedaille="Or">17</medaille>
            <medaille typeDeMedaille="Argent">10</medaille>
            <medaille typeDeMedaille="Bronze">15</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="Japon"></pays>
            <medaille typeDeMedaille="Or">12</medaille>
            <medaille typeDeMedaille="Argent">8</medaille>
            <medaille typeDeMedaille="Bronze">21</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="France"></pays>
            <medaille typeDeMedaille="Or">10</medaille>
            <medaille typeDeMedaille="Argent">18</medaille>
            <medaille typeDeMedaille="Bronze">14</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="CoreeDuSud"></pays>
            <medaille typeDeMedaille="Or">9</medaille>
            <medaille typeDeMedaille="Argent">3</medaille>
            <medaille typeDeMedaille="Bronze">9</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="Italie"></pays>
            <medaille typeDeMedaille="Or">8</medaille>
            <medaille typeDeMedaille="Argent">12</medaille>
            <medaille typeDeMedaille="Bronze">8</medaille>        
        </ligne>
        <ligne>
            <pays nomDePays="Australie"></pays>
            <medaille typeDeMedaille="Or">8</medaille>
            <medaille typeDeMedaille="Argent">11</medaille>
            <medaille typeDeMedaille="Bronze">10</medaille>        
        </ligne>
    </tableau>
</oui>

=== Randy-Bruce/XML/02_JeuxOlympique/public_html/jeuxOlympique.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE oui SYSTEM "jeuxOlympique.dtd">
<?xml-stylesheet href="jeuxOlympique.xsl" type="text/xsl" ?>
<oui>
    <tableau>
        <ligne>
            <pays nomDePays="USA">
                <medaille typeDeMedaille="Or">46</medaille>
                <medaille typeDeMedaille="Argent">37</medaille>
                <medaille typeDeMedaille="Bronze">38</medaille>   
            </pays>     
        </ligne>
        <ligne>
            <pays nomDePays="GrandeBretagne">
                <medaille typeDeMedaille="Or">27</medaille>
                <medaille typeDeMedaille="Argent">23</medaille>
                <medaille typeDeMedaille="Bronze">17</medaille>  
            </pays>      
        </ligne>
        <ligne>
            <pays nomDePays="Chine">
                <medaille typeDeMedaille="Or">26</medaille>
                <medaille typeDeMedaille="Argent">18</medaille>
                <medaille typeDeMedaille="Bronze">26</medaille>   
            </pays>     
        </ligne>
        <ligne>
            <pays nomDePays="Russie">
                <medaille typeDeMedaille="Or">19</medaille>
                <medaille typeDeMedaille="Argent">18</medaille>
                <medaille typeDeMedaille="Bronze">19</medaille>   
            </pays>     
        </ligne>
        <ligne>
            <pays nomDePays="Allemagne">
                <medaille typeDeMedaille="Or">17</medaille>
                <medaille typeDeMedaille="Argent">10</medaille>
                <medaille typeDeMedaille="Bronze">15</medaille>      
            </pays>  
        </ligne>
        <ligne>
            <pays nomDePays="Japon">
                <medaille typeDeMedaille="Or">12</medaille>
                <medaille typeDeMedaille="Argent">8</medaille>
                <medaille typeDeMedaille="Bronze">21</medaille>   
            </pays>     
        </ligne>
        <ligne>
            <pays nomDePays="France">
                <medaille typeDeMedaille="Or">10</medaille>
                <medaille typeDeMedaille="Argent">18</medaille>
                <medaille typeDeMedaille="Bronze">14</medaille>      
            </pays>  
        </ligne>
        <ligne>
            <pays nomDePays="CoreeDuSud">
                <medaille typeDeMedaille="Or">9</medaille>
                <medaille typeDeMedaille="Argent">3</medaille>
                <medaille typeDeMedaille="Bronze">9</medaille>     
            </pays>   
        </ligne>
        <ligne>
            <pays nomDePays="Italie">
                <medaille typeDeMedaille="Or">8</medaille>
                <medaille typeDeMedaille="Argent">12</medaille>
                <medaille typeDeMedaille="Bronze">8</medaille>       
            </pays> 
        </ligne>
        <ligne>
            <pays nomDePays="Australie">
                <medaille typeDeMedaille="Or">8</medaille>
                <medaille typeDeMedaille="Argent">11</medaille>
                <medaille typeDeMedaille="Bronze">10</medaille>     
            </pays>   
        </ligne>
    </tableau>
</oui>
